"""User end

Revision ID: 3e613dfa4952
Revises: c35a53c857c2
Create Date: 2023-11-11 13:18:57.542136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e613dfa4952'
down_revision: Union[str, None] = 'c35a53c857c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choices',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userfavorite',
    sa.Column('first_user', sa.Integer(), nullable=True),
    sa.Column('second_user', sa.Integer(), nullable=True),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('photo', sa.String(), nullable=False))
    op.add_column('user', sa.Column('description', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('full_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_profile')
    op.drop_column('user', 'active')
    op.drop_column('user', 'description')
    op.drop_column('user', 'photo')
    op.drop_column('user', 'age')
    op.drop_column('user', 'last_name')
    op.drop_table('userfavorite')
    op.drop_table('choices')
    # ### end Alembic commands ###
