MAX_LEIGHT_NAME = 100
MAX_LEIGHT_DESCRIPTION = 300
MAX_LEIGHT_GENDER = 1
LOG_FORM = '%(asctime)s, %(levelname)s, %(message)s'
LOG_FILEMOD = 'w'
LOG_FILENAME = 'logger.log'
TOKEN_EXECT = 'Token is invalid!'
STRAT_COMAND = 'start'
KEY_SEARCH = 'SEARCH_NEW_PAIR'
START_MESSAGE = 'Hello'
LETS_SEARCH_MESSAGE = 'LETS SEARCH'
CREATE_PROFILE = f'{START_MESSAGE}, lests create yours questionnaire'
